#pragma once
//Init cheat code
#define IO_READ_PROCESS_MEMORY_32		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xA01, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//Get modules request
#define IO_GET_MODULES					CTL_CODE(FILE_DEVICE_UNKNOWN, 0xA02, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//Setup driver
#define IO_SETUP						CTL_CODE(FILE_DEVICE_UNKNOWN, 0xA03, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)

//Encrypt XOR val
#define XOR_VAL 0x1337

typedef struct _KERNEL_READ_REQUEST32
{
	DWORD32 Address;
	DWORD64 Response;
	SIZE_T Size;
	NTSTATUS result;
} KERNEL_READ_REQUEST32, * PKERNEL_READ_REQUEST32;

typedef struct _KERNEL_GET_CLIENT_DLL
{
	DWORD32 bClient;
	DWORD32 bEngine;
	NTSTATUS result;
} KERNEL_GET_CLIENT_DLL, * PKERNEL_GET_CLIENT_DLL;

typedef struct _KERNEL_SEND_PROCESSES
{
	HANDLE gameId;
	HANDLE cheatId;
	NTSTATUS result;
} KERNEL_SEND_PROCESSES, *PKERNEL_SEND_PROCESSES;
