#pragma once
//Init cheat code
#define IO_READ_PROCESS_MEMORY_32		CTL_CODE(FILE_DEVICE_UNKNOWN, 0xA01, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


//CS GO ONLY Methods
#define IO_GET_CLIENT_DLL				CTL_CODE(FILE_DEVICE_UNKNOWN, 0xA02, METHOD_BUFFERED, FILE_SPECIAL_ACCESS)


#define XOR_VAL 0x1337

typedef struct _KERNEL_HOOK_REQUEST
{
	INT Magic;
	ULONG RequestCode;
	PVOID RequestData;
	ULONG RequestSize;	
} KERNEL_HOOK_REQUEST, *PKERNEL_HOOK_REQUEST;

typedef struct _KERNEL_READ_REQUEST32
{
	DWORD32 Address;
	DWORD64 Response;
	SIZE_T Size;
	NTSTATUS Result;
} KERNEL_READ_REQUEST32, * PKERNEL_READ_REQUEST32;

typedef struct _KERNEL_GET_CLIENT_DLL
{
	DWORD32 bClient;
	DWORD32 bEngine;
	NTSTATUS result;
} KERNEL_GET_CLIENT_DLL, * PKERNEL_GET_CLIENT_DLL;
